const livros = [
  // =========================
  // FANTASIA
  // =========================

  {
    id: 1,
    titulo: "O Hobbit",
    autor: "J. R. R. Tolkien",
    categoria: "Fantasia",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/hobbit.jpeg",
  },
  {
    id: 2,
    titulo: "O Senhor dos Anéis: A Sociedade do Anel",
    autor: "J. R. R. Tolkien",
    categoria: "Fantasia",
    preco: 59.9,
    maisVendido: true,
    imagem: "IMG/capas/o-senhor-dos-aneis-a-sociedade-do-anel.jpg",
  },
  {
    id: 3,
    titulo: "O Senhor dos Anéis: As Duas Torres",
    autor: "J. R. R. Tolkien",
    categoria: "Fantasia",
    preco: 59.9,
    maisVendido: false,
    imagem: "IMG/capas/o-senhor-dos-aneis-as-duas-torres.jpg",
  },
  {
    id: 4,
    titulo: "O Senhor dos Anéis: O Retorno do Rei",
    autor: "J. R. R. Tolkien",
    categoria: "Fantasia",
    preco: 59.9,
    maisVendido: true,
    imagem: "IMG/capas/o-senhor-dos-aneis-o-retorno-do-rei.jpg",
  },
  {
    id: 5,
    titulo: "Harry Potter e a Pedra Filosofal",
    autor: "J. K. Rowling",
    categoria: "Fantasia",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/harry-potter-e-a-pedra-filosofal.jpg",
  },
  {
    id: 6,
    titulo: "Harry Potter e a Câmara Secreta",
    autor: "J. K. Rowling",
    categoria: "Fantasia",
    preco: 44.9,
    maisVendido: false,
    imagem: "IMG/capas/harry-potter-e-a-camara-secreta.jpg",
  },
  {
    id: 7,
    titulo: "Harry Potter e o Prisioneiro de Azkaban",
    autor: "J. K. Rowling",
    categoria: "Fantasia",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/harry-potter-e-o-prisioneiro-de-azkaban.jpg",
  },
  {
    id: 8,
    titulo: "As Crônicas de Nárnia",
    autor: "C. S. Lewis",
    categoria: "Fantasia",
    preco: 69.9,
    maisVendido: true,
    imagem: "IMG/capas/as-cronicas-de-narnia.jpg",
  },
  {
    id: 9,
    titulo: "O Nome do Vento",
    autor: "Patrick Rothfuss",
    categoria: "Fantasia",
    preco: 54.9,
    maisVendido: false,
    imagem: "IMG/capas/o-nome-do-vento.jpg",
  },
  {
    id: 10,
    titulo: "Eragon",
    autor: "Christopher Paolini",
    categoria: "Fantasia",
    preco: 42.9,
    maisVendido: false,
    imagem: "IMG/capas/eragon.jpg",
  },
  {
    id: 11,
    titulo: "Mistborn: O Império Final",
    autor: "Brandon Sanderson",
    categoria: "Fantasia",
    preco: 59.9,
    maisVendido: true,
    imagem: "IMG/capas/mistborn-o-imperio-final.jpg",
  },
  {
    id: 12,
    titulo: "O Caminho dos Reis",
    autor: "Brandon Sanderson",
    categoria: "Fantasia",
    preco: 79.9,
    maisVendido: false,
    imagem: "IMG/capas/o-caminho-dos-reis.jpg",
  },
  {
    id: 13,
    titulo: "A Bússola de Ouro",
    autor: "Philip Pullman",
    categoria: "Fantasia",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/a-bussola-de-ouro.jpg",
  },
  {
    id: 14,
    titulo: "O Oceano no Fim do Caminho",
    autor: "Neil Gaiman",
    categoria: "Fantasia",
    preco: 42.9,
    maisVendido: true,
    imagem: "IMG/capas/o-oceano-no-fim-do-caminho.jpg",
  },
  {
    id: 15,
    titulo: "Deuses Americanos",
    autor: "Neil Gaiman",
    categoria: "Fantasia",
    preco: 59.9,
    maisVendido: false,
    imagem: "IMG/capas/deuses-americanos.jpg",
  },

  // =========================
  // FICÇÃO CIENTÍFICA
  // =========================

  {
    id: 16,
    titulo: "Duna",
    autor: "Frank Herbert",
    categoria: "Ficção Científica",
    preco: 69.9,
    maisVendido: true,
    imagem: "IMG/capas/duna.jpg",
  },
  {
    id: 17,
    titulo: "Neuromancer",
    autor: "William Gibson",
    categoria: "Ficção Científica",
    preco: 49.9,
    maisVendido: false,
    imagem: "IMG/capas/neuromancer.jpg",
  },
  {
    id: 18,
    titulo: "Eu, Robô",
    autor: "Isaac Asimov",
    categoria: "Ficção Científica",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/eu-robo.jpg",
  },
  {
    id: 19,
    titulo: "Fundação",
    autor: "Isaac Asimov",
    categoria: "Ficção Científica",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/fundacao.jpg",
  },
  {
    id: 20,
    titulo: "2001: Uma Odisseia no Espaço",
    autor: "Arthur C. Clarke",
    categoria: "Ficção Científica",
    preco: 47.9,
    maisVendido: false,
    imagem: "IMG/capas/2001-uma-odisseia-no-espaco.jpg",
  },
  {
    id: 21,
    titulo: "Solaris",
    autor: "Stanislaw Lem",
    categoria: "Ficção Científica",
    preco: 42.9,
    maisVendido: false,
    imagem: "IMG/capas/solaris.jpg",
  },
  {
    id: 22,
    titulo: "O Fim da Infância",
    autor: "Arthur C. Clarke",
    categoria: "Ficção Científica",
    preco: 45.9,
    maisVendido: false,
    imagem: "IMG/capas/o-fim-da-infancia.jpg",
  },
  {
    id: 23,
    titulo: "Admirável Mundo Novo",
    autor: "Aldous Huxley",
    categoria: "Ficção Científica",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/admiravel-mundo-novo.jpg",
  },
  {
    id: 24,
    titulo: "A Máquina do Tempo",
    autor: "H. G. Wells",
    categoria: "Ficção Científica",
    preco: 34.9,
    maisVendido: false,
    imagem: "IMG/capas/a-maquina-do-tempo.jpg",
  },
  {
    id: 25,
    titulo: "Guerra dos Mundos",
    autor: "H. G. Wells",
    categoria: "Ficção Científica",
    preco: 36.9,
    maisVendido: true,
    imagem: "IMG/capas/guerra-dos-mundos.jpg",
  },

  // =========================
  // DISTOPIA
  // =========================

  {
    id: 26,
    titulo: "1984",
    autor: "George Orwell",
    categoria: "Distopia",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/1984.jpg",
  },
  {
    id: 27,
    titulo: "A Revolução dos Bichos",
    autor: "George Orwell",
    categoria: "Distopia",
    preco: 29.9,
    maisVendido: true,
    imagem: "IMG/capas/a-revolucao-dos-bichos.jpg",
  },
  {
    id: 28,
    titulo: "Fahrenheit 451",
    autor: "Ray Bradbury",
    categoria: "Distopia",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/fahrenheit-451.jpg",
  },
  {
    id: 29,
    titulo: "Jogos Vorazes",
    autor: "Suzanne Collins",
    categoria: "Distopia",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/jogos-vorazes.jpg",
  },
  {
    id: 30,
    titulo: "A Esperança",
    autor: "Suzanne Collins",
    categoria: "Distopia",
    preco: 49.9,
    maisVendido: false,
    imagem: "IMG/capas/a-esperanca.jpg",
  },
  {
    id: 31,
    titulo: "Divergente",
    autor: "Veronica Roth",
    categoria: "Distopia",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/divergente.jpg",
  },
  {
    id: 32,
    titulo: "O Conto da Aia",
    autor: "Margaret Atwood",
    categoria: "Distopia",
    preco: 54.9,
    maisVendido: true,
    imagem: "IMG/capas/o-conto-da-aia.jpg",
  },
  {
    id: 33,
    titulo: "Nós",
    autor: "Ievguêni Zamiátin",
    categoria: "Distopia",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/nos.jpg",
  },
  {
    id: 34,
    titulo: "V de Vingança",
    autor: "Alan Moore",
    categoria: "Distopia",
    preco: 69.9,
    maisVendido: false,
    imagem: "IMG/capas/v-de-vinganca.jpg",
  },
  {
    id: 35,
    titulo: "Laranja Mecânica",
    autor: "Anthony Burgess",
    categoria: "Distopia",
    preco: 44.9,
    maisVendido: false,
    imagem: "IMG/capas/laranja-mecanica.jpg",
  },

  // =========================
  // ROMANCE
  // =========================

  {
    id: 36,
    titulo: "Orgulho e Preconceito",
    autor: "Jane Austen",
    categoria: "Romance",
    preco: 34.9,
    maisVendido: true,
    imagem: "IMG/capas/orgulho-e-preconceito.jpg",
  },
  {
    id: 37,
    titulo: "Razão e Sensibilidade",
    autor: "Jane Austen",
    categoria: "Romance",
    preco: 34.9,
    maisVendido: false,
    imagem: "IMG/capas/razao-e-sensibilidade.jpg",
  },
  {
    id: 38,
    titulo: "Como Eu Era Antes de Você",
    autor: "Jojo Moyes",
    categoria: "Romance",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/como-eu-era-antes-de-voce.jpg",
  },
  {
    id: 39,
    titulo: "Um Dia",
    autor: "David Nicholls",
    categoria: "Romance",
    preco: 42.9,
    maisVendido: true,
    imagem: "IMG/capas/um-dia.jpg",
  },
  {
    id: 40,
    titulo: "A Hipótese do Amor",
    autor: "Ali Hazelwood",
    categoria: "Romance",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/a-hipotese-do-amor.jpg",
  },
  {
    id: 41,
    titulo: "Melhor do que nos Filmes",
    autor: "Lynn Painter",
    categoria: "Romance",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/melhor-do-que-nos-filmes.jpg",
  },
  {
    id: 42,
    titulo: "O Amor Não é Óbvio",
    autor: "Elayne Baeta",
    categoria: "Romance",
    preco: 42.9,
    maisVendido: false,
    imagem: "IMG/capas/o-amor-nao-e-obvio.jpg",
  },
  {
    id: 43,
    titulo: "Vermelho, Branco e Sangue Azul",
    autor: "Casey McQuiston",
    categoria: "Romance",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/vermelho-branco-e-sangue-azul.jpg",
  },
  {
    id: 44,
    titulo: "Eleanor & Park",
    autor: "Rainbow Rowell",
    categoria: "Romance",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/eleanor-park.jpg",
  },
  {
    id: 45,
    titulo: "Pessoas Normais",
    autor: "Sally Rooney",
    categoria: "Romance",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/pessoas-normais.jpg",
  },

  // =========================
  // DRAMA
  // =========================

  {
    id: 46,
    titulo: "A Culpa é das Estrelas",
    autor: "John Green",
    categoria: "Drama",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/a-culpa-e-das-estrelas.jpg",
  },
  {
    id: 47,
    titulo: "Extraordinário",
    autor: "R. J. Palacio",
    categoria: "Drama",
    preco: 42.9,
    maisVendido: true,
    imagem: "IMG/capas/extraordinario.jpg",
  },
  {
    id: 48,
    titulo: "O Menino do Pijama Listrado",
    autor: "John Boyne",
    categoria: "Drama",
    preco: 34.9,
    maisVendido: true,
    imagem: "IMG/capas/o-menino-do-pijama-listrado.jpg",
  },
  {
    id: 49,
    titulo: "As Vantagens de Ser Invisível",
    autor: "Stephen Chbosky",
    categoria: "Drama",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/as-vantagens-de-ser-invisivel.jpg",
  },
  {
    id: 50,
    titulo: "Flores para Algernon",
    autor: "Daniel Keyes",
    categoria: "Drama",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/flores-para-algernon.jpg",
  },
  {
    id: 51,
    titulo: "O Sol é Para Todos",
    autor: "Harper Lee",
    categoria: "Drama",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/o-sol-e-para-todos.jpg",
  },
  {
    id: 52,
    titulo: "A Menina que Roubava Livros",
    autor: "Markus Zusak",
    categoria: "Drama",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/a-menina-que-roubava-livros.jpg",
  },
  {
    id: 53,
    titulo: "Marley & Eu",
    autor: "John Grogan",
    categoria: "Drama",
    preco: 34.9,
    maisVendido: false,
    imagem: "IMG/capas/marley-eu.jpg",
  },
  {
    id: 54,
    titulo: "O Caçador de Pipas",
    autor: "Khaled Hosseini",
    categoria: "Drama",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/o-cacador-de-pipas.jpg",
  },
  {
    id: 55,
    titulo: "Mil Sóis Esplêndidos",
    autor: "Khaled Hosseini",
    categoria: "Drama",
    preco: 49.9,
    maisVendido: false,
    imagem: "IMG/capas/mil-sois-esplendidos.jpg",
  },

  // =========================
  // AVENTURA
  // =========================

  {
    id: 56,
    titulo: "A Ilha do Tesouro",
    autor: "Robert Louis Stevenson",
    categoria: "Aventura",
    preco: 34.9,
    maisVendido: true,
    imagem: "IMG/capas/a-ilha-do-tesouro.jpg",
  },
  {
    id: 57,
    titulo: "Robinson Crusoé",
    autor: "Daniel Defoe",
    categoria: "Aventura",
    preco: 32.9,
    maisVendido: false,
    imagem: "IMG/capas/robinson-crusoe.jpg",
  },
  {
    id: 58,
    titulo: "Viagem ao Centro da Terra",
    autor: "Júlio Verne",
    categoria: "Aventura",
    preco: 36.9,
    maisVendido: true,
    imagem: "IMG/capas/viagem-ao-centro-da-terra.jpg",
  },
  {
    id: 59,
    titulo: "Vinte Mil Léguas Submarinas",
    autor: "Júlio Verne",
    categoria: "Aventura",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/vinte-mil-leguas-submarinas.jpg",
  },
  {
    id: 60,
    titulo: "As Aventuras de Tom Sawyer",
    autor: "Mark Twain",
    categoria: "Aventura",
    preco: 34.9,
    maisVendido: true,
    imagem: "IMG/capas/as-aventuras-de-tom-sawyer.jpg",
  },
  {
    id: 61,
    titulo: "O Conde de Monte Cristo",
    autor: "Alexandre Dumas",
    categoria: "Aventura",
    preco: 59.9,
    maisVendido: true,
    imagem: "IMG/capas/o-conde-de-monte-cristo.jpg",
  },
  {
    id: 62,
    titulo: "Os Três Mosqueteiros",
    autor: "Alexandre Dumas",
    categoria: "Aventura",
    preco: 49.9,
    maisVendido: false,
    imagem: "IMG/capas/os-tres-mosqueteiros.jpg",
  },
  {
    id: 63,
    titulo: "As Minas do Rei Salomão",
    autor: "H. Rider Haggard",
    categoria: "Aventura",
    preco: 37.9,
    maisVendido: false,
    imagem: "IMG/capas/as-minas-do-rei-salomao.jpg",
  },
  {
    id: 64,
    titulo: "O Último dos Moicanos",
    autor: "James Fenimore Cooper",
    categoria: "Aventura",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/o-ultimo-dos-moicanos.jpg",
  },
  {
    id: 65,
    titulo: "O Mundo Perdido",
    autor: "Arthur Conan Doyle",
    categoria: "Aventura",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/o-mundo-perdido.jpg",
  },

  // =========================
  // MISTÉRIO E SUSPENSE
  // =========================

  {
    id: 66,
    titulo: "O Assassinato no Expresso do Oriente",
    autor: "Agatha Christie",
    categoria: "Mistério",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/o-assassinato-no-expresso-do-oriente.jpg",
  },
  {
    id: 67,
    titulo: "E Não Sobrou Nenhum",
    autor: "Agatha Christie",
    categoria: "Mistério",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/e-nao-sobrou-nenhum.jpg",
  },
  {
    id: 68,
    titulo: "Morte no Nilo",
    autor: "Agatha Christie",
    categoria: "Mistério",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/morte-no-nilo.jpg",
  },
  {
    id: 69,
    titulo: "O Código Da Vinci",
    autor: "Dan Brown",
    categoria: "Suspense",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/o-codigo-da-vinci.jpg",
  },
  {
    id: 70,
    titulo: "Anjos e Demônios",
    autor: "Dan Brown",
    categoria: "Suspense",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/anjos-e-demonios.jpg",
  },
  {
    id: 71,
    titulo: "Garota Exemplar",
    autor: "Gillian Flynn",
    categoria: "Suspense",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/garota-exemplar.jpg",
  },
  {
    id: 72,
    titulo: "A Mulher na Janela",
    autor: "A. J. Finn",
    categoria: "Suspense",
    preco: 44.9,
    maisVendido: false,
    imagem: "IMG/capas/a-mulher-na-janela.jpg",
  },
  {
    id: 73,
    titulo: "Antes de Dormir",
    autor: "S. J. Watson",
    categoria: "Suspense",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/antes-de-dormir.jpg",
  },
  {
    id: 74,
    titulo: "O Silêncio dos Inocentes",
    autor: "Thomas Harris",
    categoria: "Suspense",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/o-silencio-dos-inocentes.jpg",
  },
  {
    id: 75,
    titulo: "A Paciente Silenciosa",
    autor: "Alex Michaelides",
    categoria: "Suspense",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/a-paciente-silenciosa.jpg",
  },

  // =========================
  // TERROR
  // =========================

  {
    id: 76,
    titulo: "It: A Coisa",
    autor: "Stephen King",
    categoria: "Terror",
    preco: 59.9,
    maisVendido: true,
    imagem: "IMG/capas/it-a-coisa.jpg",
  },
  {
    id: 77,
    titulo: "O Iluminado",
    autor: "Stephen King",
    categoria: "Terror",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/o-iluminado.jpg",
  },
  {
    id: 78,
    titulo: "Carrie",
    autor: "Stephen King",
    categoria: "Terror",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/carrie.jpg",
  },
  {
    id: 79,
    titulo: "Cemitério Maldito",
    autor: "Stephen King",
    categoria: "Terror",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/cemiterio-maldito.jpg",
  },
  {
    id: 80,
    titulo: "O Exorcista",
    autor: "William Peter Blatty",
    categoria: "Terror",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/o-exorcista.jpg",
  },
  {
    id: 81,
    titulo: "Drácula",
    autor: "Bram Stoker",
    categoria: "Terror",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/dracula.jpg",
  },
  {
    id: 82,
    titulo: "Frankenstein",
    autor: "Mary Shelley",
    categoria: "Terror",
    preco: 34.9,
    maisVendido: false,
    imagem: "IMG/capas/frankenstein.jpg",
  },
  {
    id: 83,
    titulo: "O Chamado",
    autor: "Kōji Suzuki",
    categoria: "Terror",
    preco: 42.9,
    maisVendido: false,
    imagem: "IMG/capas/o-chamado.jpg",
  },
  {
    id: 84,
    titulo: "A Assombração da Casa da Colina",
    autor: "Shirley Jackson",
    categoria: "Terror",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/a-assombracao-da-casa-da-colina.jpg",
  },
  {
    id: 85,
    titulo: "Coraline",
    autor: "Neil Gaiman",
    categoria: "Terror",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/coraline.jpg",
  },

  // =========================
  // AUTOAJUDA
  // =========================

  {
    id: 86,
    titulo: "Hábitos Atômicos",
    autor: "James Clear",
    categoria: "Autoajuda",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/habitos-atomicos.jpg",
  },
  {
    id: 87,
    titulo: "O Poder do Hábito",
    autor: "Charles Duhigg",
    categoria: "Autoajuda",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/o-poder-do-habito.jpg",
  },
  {
    id: 88,
    titulo: "Mindset",
    autor: "Carol S. Dweck",
    categoria: "Autoajuda",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/mindset.jpg",
  },
  {
    id: 89,
    titulo: "Essencialismo",
    autor: "Greg McKeown",
    categoria: "Autoajuda",
    preco: 44.9,
    maisVendido: false,
    imagem: "IMG/capas/essencialismo.jpg",
  },
  {
    id: 90,
    titulo: "A Coragem de Ser Imperfeito",
    autor: "Brené Brown",
    categoria: "Autoajuda",
    preco: 42.9,
    maisVendido: true,
    imagem: "IMG/capas/a-coragem-de-ser-imperfeito.jpg",
  },
  {
    id: 91,
    titulo: "O Poder do Agora",
    autor: "Eckhart Tolle",
    categoria: "Autoajuda",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/o-poder-do-agora.jpg",
  },
  {
    id: 92,
    titulo: "Como Fazer Amigos e Influenciar Pessoas",
    autor: "Dale Carnegie",
    categoria: "Autoajuda",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/como-fazer-amigos-e-influenciar-pessoas.jpg",
  },
  {
    id: 93,
    titulo: "Mais Esperto que o Diabo",
    autor: "Napoleon Hill",
    categoria: "Autoajuda",
    preco: 44.9,
    maisVendido: false,
    imagem: "IMG/capas/mais-esperto-que-o-diabo.jpg",
  },
  {
    id: 94,
    titulo: "Quem Pensa Enriquece",
    autor: "Napoleon Hill",
    categoria: "Autoajuda",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/quem-pensa-enriquece.jpg",
  },
  {
    id: 95,
    titulo: "O Segredo",
    autor: "Rhonda Byrne",
    categoria: "Autoajuda",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/o-segredo.jpg",
  },

  // =========================
  // HISTÓRIA
  // =========================

  {
    id: 96,
    titulo: "Sapiens",
    autor: "Yuval Noah Harari",
    categoria: "História",
    preco: 59.9,
    maisVendido: true,
    imagem: "IMG/capas/sapiens.jpg",
  },
  {
    id: 97,
    titulo: "Homo Deus",
    autor: "Yuval Noah Harari",
    categoria: "História",
    preco: 59.9,
    maisVendido: false,
    imagem: "IMG/capas/homo-deus.jpg",
  },
  {
    id: 98,
    titulo: "21 Lições para o Século 21",
    autor: "Yuval Noah Harari",
    categoria: "História",
    preco: 54.9,
    maisVendido: true,
    imagem: "IMG/capas/21-licoes-para-o-seculo-21.jpg",
  },
  {
    id: 99,
    titulo: "Uma Breve História do Tempo",
    autor: "Stephen Hawking",
    categoria: "História",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/uma-breve-historia-do-tempo.jpg",
  },
  {
    id: 100,
    titulo: "Armas, Germes e Aço",
    autor: "Jared Diamond",
    categoria: "História",
    preco: 59.9,
    maisVendido: false,
    imagem: "IMG/capas/armas-germes-e-aco.jpg",
  },

  // =========================
  // FILOSOFIA
  // =========================

  {
    id: 101,
    titulo: "O Banquete",
    autor: "Platão",
    categoria: "Filosofia",
    preco: 29.9,
    maisVendido: false,
    imagem: "IMG/capas/o-banquete.jpg",
  },
  {
    id: 102,
    titulo: "A República",
    autor: "Platão",
    categoria: "Filosofia",
    preco: 34.9,
    maisVendido: true,
    imagem: "IMG/capas/a-republica.jpg",
  },
  {
    id: 103,
    titulo: "Meditações",
    autor: "Marco Aurélio",
    categoria: "Filosofia",
    preco: 32.9,
    maisVendido: true,
    imagem: "IMG/capas/meditacoes.jpg",
  },
  {
    id: 104,
    titulo: "O Príncipe",
    autor: "Nicolau Maquiavel",
    categoria: "Filosofia",
    preco: 29.9,
    maisVendido: true,
    imagem: "IMG/capas/o-principe.jpg",
  },
  {
    id: 105,
    titulo: "Assim Falou Zaratustra",
    autor: "Friedrich Nietzsche",
    categoria: "Filosofia",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/assim-falou-zaratustra.jpg",
  },
  {
    id: 106,
    titulo: "Além do Bem e do Mal",
    autor: "Friedrich Nietzsche",
    categoria: "Filosofia",
    preco: 34.9,
    maisVendido: false,
    imagem: "IMG/capas/alem-do-bem-e-do-mal.jpg",
  },
  {
    id: 107,
    titulo: "O Mundo de Sofia",
    autor: "Jostein Gaarder",
    categoria: "Filosofia",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/o-mundo-de-sofia.jpg",
  },
  {
    id: 108,
    titulo: "O Mito de Sísifo",
    autor: "Albert Camus",
    categoria: "Filosofia",
    preco: 34.9,
    maisVendido: false,
    imagem: "IMG/capas/o-mito-de-sisifo.jpg",
  },

  // =========================
  // POESIA
  // =========================

  {
    id: 109,
    titulo: "Alguma Poesia",
    autor: "Carlos Drummond de Andrade",
    categoria: "Poesia",
    preco: 34.9,
    maisVendido: true,
    imagem: "IMG/capas/alguma-poesia.jpg",
  },
  {
    id: 110,
    titulo: "Toda Poesia",
    autor: "Paulo Leminski",
    categoria: "Poesia",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/toda-poesia.jpg",
  },
  {
    id: 111,
    titulo: "Sonetos",
    autor: "Luís de Camões",
    categoria: "Poesia",
    preco: 29.9,
    maisVendido: false,
    imagem: "IMG/capas/sonetos.jpg",
  },
  {
    id: 112,
    titulo: "Antologia Poética",
    autor: "Cecília Meireles",
    categoria: "Poesia",
    preco: 34.9,
    maisVendido: false,
    imagem: "IMG/capas/antologia-poetica.jpg",
  },
  {
    id: 113,
    titulo: "Sentimento do Mundo",
    autor: "Carlos Drummond de Andrade",
    categoria: "Poesia",
    preco: 32.9,
    maisVendido: true,
    imagem: "IMG/capas/sentimento-do-mundo.jpg",
  },
  {
    id: 114,
    titulo: "Livro Sobre Nada",
    autor: "Manoel de Barros",
    categoria: "Poesia",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/livro-sobre-nada.jpg",
  },

  // =========================
  // BIOGRAFIA
  // =========================

  {
    id: 115,
    titulo: "Steve Jobs",
    autor: "Walter Isaacson",
    categoria: "Biografia",
    preco: 69.9,
    maisVendido: true,
    imagem: "IMG/capas/steve-jobs.jpg",
  },
  {
    id: 116,
    titulo: "Einstein: Sua Vida, Seu Universo",
    autor: "Walter Isaacson",
    categoria: "Biografia",
    preco: 64.9,
    maisVendido: false,
    imagem: "IMG/capas/einstein-sua-vida-seu-universo.jpg",
  },
  {
    id: 117,
    titulo: "Leonardo da Vinci",
    autor: "Walter Isaacson",
    categoria: "Biografia",
    preco: 69.9,
    maisVendido: true,
    imagem: "IMG/capas/leonardo-da-vinci.jpg",
  },
  {
    id: 118,
    titulo: "Pelé",
    autor: "Pelé",
    categoria: "Biografia",
    preco: 59.9,
    maisVendido: true,
    imagem: "IMG/capas/pele.jpg",
  },
  {
    id: 119,
    titulo: "Minha História",
    autor: "Michelle Obama",
    categoria: "Biografia",
    preco: 59.9,
    maisVendido: true,
    imagem: "IMG/capas/minha-historia.jpg",
  },
  {
    id: 120,
    titulo: "Longa Caminhada até a Liberdade",
    autor: "Nelson Mandela",
    categoria: "Biografia",
    preco: 54.9,
    maisVendido: false,
    imagem: "IMG/capas/longa-caminhada-ate-a-liberdade.jpg",
  },

  // =========================
  // PSICOLOGIA
  // =========================

  {
    id: 121,
    titulo: "Rápido e Devagar",
    autor: "Daniel Kahneman",
    categoria: "Psicologia",
    preco: 59.9,
    maisVendido: true,
    imagem: "IMG/capas/rapido-e-devagar.jpg",
  },
  {
    id: 122,
    titulo: "O Homem que Confundiu Sua Mulher com um Chapéu",
    autor: "Oliver Sacks",
    categoria: "Psicologia",
    preco: 44.9,
    maisVendido: false,
    imagem: "IMG/capas/o-homem-que-confundiu-sua-mulher-com-um-chapeu.jpg",
  },
  {
    id: 123,
    titulo: "Inteligência Emocional",
    autor: "Daniel Goleman",
    categoria: "Psicologia",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/inteligencia-emocional.jpg",
  },
  {
    id: 124,
    titulo: "O Animal Social",
    autor: "Elliot Aronson",
    categoria: "Psicologia",
    preco: 59.9,
    maisVendido: false,
    imagem: "IMG/capas/o-animal-social.jpg",
  },
  {
    id: 125,
    titulo: "A Psicologia Financeira",
    autor: "Morgan Housel",
    categoria: "Psicologia",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/a-psicologia-financeira.jpg",
  },

  // =========================
  // NEGÓCIOS
  // =========================

  {
    id: 126,
    titulo: "Pai Rico, Pai Pobre",
    autor: "Robert Kiyosaki",
    categoria: "Negócios",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/pai-rico-pai-pobre.jpg",
  },
  {
    id: 127,
    titulo: "Do Mil ao Milhão",
    autor: "Thiago Nigro",
    categoria: "Negócios",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/do-mil-ao-milhao.jpg",
  },
  {
    id: 128,
    titulo: "O Homem Mais Rico da Babilônia",
    autor: "George S. Clason",
    categoria: "Negócios",
    preco: 34.9,
    maisVendido: true,
    imagem: "IMG/capas/o-homem-mais-rico-da-babilonia.jpg",
  },
  {
    id: 129,
    titulo: "A Startup Enxuta",
    autor: "Eric Ries",
    categoria: "Negócios",
    preco: 54.9,
    maisVendido: false,
    imagem: "IMG/capas/a-startup-enxuta.jpg",
  },
  {
    id: 130,
    titulo: "De Zero a Um",
    autor: "Peter Thiel",
    categoria: "Negócios",
    preco: 49.9,
    maisVendido: false,
    imagem: "IMG/capas/de-zero-a-um.jpg",
  },
  {
    id: 131,
    titulo: "Empresas Feitas para Vencer",
    autor: "Jim Collins",
    categoria: "Negócios",
    preco: 54.9,
    maisVendido: false,
    imagem: "IMG/capas/empresas-feitas-para-vencer.jpg",
  },

  // =========================
  // TECNOLOGIA
  // =========================

  {
    id: 132,
    titulo: "Código Limpo",
    autor: "Robert C. Martin",
    categoria: "Tecnologia",
    preco: 89.9,
    maisVendido: true,
    imagem: "IMG/capas/codigo-limpo.jpg",
  },
  {
    id: 133,
    titulo: "O Programador Pragmático",
    autor: "Andrew Hunt e David Thomas",
    categoria: "Tecnologia",
    preco: 84.9,
    maisVendido: true,
    imagem: "IMG/capas/o-programador-pragmatico.jpg",
  },
  {
    id: 134,
    titulo: "Entendendo Algoritmos",
    autor: "Aditya Bhargava",
    categoria: "Tecnologia",
    preco: 69.9,
    maisVendido: true,
    imagem: "IMG/capas/entendendo-algoritmos.jpg",
  },
  {
    id: 135,
    titulo: "Use a Cabeça! Java",
    autor: "Kathy Sierra e Bert Bates",
    categoria: "Tecnologia",
    preco: 79.9,
    maisVendido: false,
    imagem: "IMG/capas/use-a-cabeca-java.jpg",
  },
  {
    id: 136,
    titulo: "JavaScript: O Guia Definitivo",
    autor: "David Flanagan",
    categoria: "Tecnologia",
    preco: 99.9,
    maisVendido: false,
    imagem: "IMG/capas/javascript-o-guia-definitivo.jpg",
  },
  {
    id: 137,
    titulo: "Não Me Faça Pensar",
    autor: "Steve Krug",
    categoria: "Tecnologia",
    preco: 69.9,
    maisVendido: true,
    imagem: "IMG/capas/nao-me-faca-pensar.jpg",
  },

  // =========================
  // INFANTOJUVENIL
  // =========================

  {
    id: 138,
    titulo: "Diário de um Banana",
    autor: "Jeff Kinney",
    categoria: "Infantojuvenil",
    preco: 34.9,
    maisVendido: true,
    imagem: "IMG/capas/diario-de-um-banana.jpg",
  },
  {
    id: 139,
    titulo: "Percy Jackson e o Ladrão de Raios",
    autor: "Rick Riordan",
    categoria: "Infantojuvenil",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/percy-jackson-e-o-ladrao-de-raios.jpg",
  },
  {
    id: 140,
    titulo: "Percy Jackson e o Mar de Monstros",
    autor: "Rick Riordan",
    categoria: "Infantojuvenil",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/percy-jackson-e-o-mar-de-monstros.jpg",
  },
  {
    id: 142,
    titulo: "O Pequeno Príncipe",
    autor: "Antoine de Saint-Exupéry",
    categoria: "Infantojuvenil",
    preco: 29.9,
    maisVendido: true,
    imagem: "IMG/capas/o-pequeno-principe.jpg",
  },
  {
    id: 143,
    titulo: "Desventuras em Série: Mau Começo",
    autor: "Lemony Snicket",
    categoria: "Infantojuvenil",
    preco: 34.9,
    maisVendido: false,
    imagem: "IMG/capas/desventuras-em-serie-mau-comeco.jpg",
  },

  // =========================
  // INFANTIL
  // =========================

  {
    id: 144,
    titulo: "O Menino Maluquinho",
    autor: "Ziraldo",
    categoria: "Infantil",
    preco: 29.9,
    maisVendido: true,
    imagem: "IMG/capas/o-menino-maluquinho.jpg",
  },
  {
    id: 145,
    titulo: "Marcelo, Marmelo, Martelo",
    autor: "Ruth Rocha",
    categoria: "Infantil",
    preco: 27.9,
    maisVendido: true,
    imagem: "IMG/capas/marcelo-marmelo-martelo.jpg",
  },
  {
    id: 146,
    titulo: "A Bolsa Amarela",
    autor: "Lygia Bojunga",
    categoria: "Infantil",
    preco: 32.9,
    maisVendido: true,
    imagem: "IMG/capas/a-bolsa-amarela.jpg",
  },
  {
    id: 147,
    titulo: "Reinações de Narizinho",
    autor: "Monteiro Lobato",
    categoria: "Infantil",
    preco: 34.9,
    maisVendido: false,
    imagem: "IMG/capas/reinacoes-de-narizinho.jpg",
  },
  {
    id: 148,
    titulo: "O Sítio do Picapau Amarelo",
    autor: "Monteiro Lobato",
    categoria: "Infantil",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/o-sitio-do-picapau-amarelo.jpg",
  },

  // =========================
  // CLÁSSICOS
  // =========================

  {
    id: 149,
    titulo: "Dom Casmurro",
    autor: "Machado de Assis",
    categoria: "Clássico",
    preco: 29.9,
    maisVendido: true,
    imagem: "IMG/capas/dom-casmurro.jpg",
  },
  {
    id: 150,
    titulo: "Memórias Póstumas de Brás Cubas",
    autor: "Machado de Assis",
    categoria: "Clássico",
    preco: 29.9,
    maisVendido: true,
    imagem: "IMG/capas/memorias-postumas-de-bras-cubas.jpg",
  },
  {
    id: 151,
    titulo: "O Cortiço",
    autor: "Aluísio Azevedo",
    categoria: "Clássico",
    preco: 29.9,
    maisVendido: false,
    imagem: "IMG/capas/o-cortico.jpg",
  },
  {
    id: 152,
    titulo: "Iracema",
    autor: "José de Alencar",
    categoria: "Clássico",
    preco: 27.9,
    maisVendido: false,
    imagem: "IMG/capas/iracema.jpg",
  },
  {
    id: 153,
    titulo: "Grande Sertão: Veredas",
    autor: "João Guimarães Rosa",
    categoria: "Clássico",
    preco: 49.9,
    maisVendido: false,
    imagem: "IMG/capas/grande-sertao-veredas.jpg",
  },
  {
    id: 154,
    titulo: "A Moreninha",
    autor: "Joaquim Manuel de Macedo",
    categoria: "Clássico",
    preco: 27.9,
    maisVendido: false,
    imagem: "IMG/capas/a-moreninha.jpg",
  },
  {
    id: 155,
    titulo: "Os Miseráveis",
    autor: "Victor Hugo",
    categoria: "Clássico",
    preco: 59.9,
    maisVendido: true,
    imagem: "IMG/capas/os-miseraveis.jpg",
  },
  {
    id: 156,
    titulo: "O Retrato de Dorian Gray",
    autor: "Oscar Wilde",
    categoria: "Clássico",
    preco: 34.9,
    maisVendido: true,
    imagem: "IMG/capas/o-retrato-de-dorian-gray.jpg",
  },
  {
    id: 157,
    titulo: "Crime e Castigo",
    autor: "Fiódor Dostoiévski",
    categoria: "Clássico",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/crime-e-castigo.jpg",
  },
  {
    id: 158,
    titulo: "Anna Kariênina",
    autor: "Liev Tolstói",
    categoria: "Clássico",
    preco: 54.9,
    maisVendido: false,
    imagem: "IMG/capas/anna-karienina.jpg",
  },

  // =========================
  // COMÉDIA
  // =========================

  {
    id: 159,
    titulo: "O Guia do Mochileiro das Galáxias",
    autor: "Douglas Adams",
    categoria: "Comédia",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/o-guia-do-mochileiro-das-galaxias.jpg",
  },
  {
    id: 160,
    titulo: "O Restaurante no Fim do Universo",
    autor: "Douglas Adams",
    categoria: "Comédia",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/o-restaurante-no-fim-do-universo.jpg",
  },
  {
    id: 161,
    titulo: "As Mentiras que os Homens Contam",
    autor: "Luis Fernando Verissimo",
    categoria: "Comédia",
    preco: 34.9,
    maisVendido: true,
    imagem: "IMG/capas/as-mentiras-que-os-homens-contam.jpg",
  },
  {
    id: 162,
    titulo: "Comédias para se Ler na Escola",
    autor: "Luis Fernando Verissimo",
    categoria: "Comédia",
    preco: 32.9,
    maisVendido: false,
    imagem: "IMG/capas/comedias-para-se-ler-na-escola.jpg",
  },
  {
    id: 163,
    titulo: "O Auto da Compadecida",
    autor: "Ariano Suassuna",
    categoria: "Comédia",
    preco: 34.9,
    maisVendido: true,
    imagem: "IMG/capas/o-auto-da-compadecida.jpg",
  },

  // =========================
  // MITOLOGIA
  // =========================

  {
    id: 164,
    titulo: "Mitologia Nórdica",
    autor: "Neil Gaiman",
    categoria: "Mitologia",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/mitologia-nordica.jpg",
  },
  {
    id: 165,
    titulo: "Mitos Gregos",
    autor: "Robert Graves",
    categoria: "Mitologia",
    preco: 54.9,
    maisVendido: false,
    imagem: "IMG/capas/mitos-gregos.jpg",
  },
  {
    id: 166,
    titulo: "O Livro da Mitologia",
    autor: "Thomas Bulfinch",
    categoria: "Mitologia",
    preco: 49.9,
    maisVendido: false,
    imagem: "IMG/capas/o-livro-da-mitologia.jpg",
  },
  {
    id: 167,
    titulo: "Percy Jackson e os Deuses Gregos",
    autor: "Rick Riordan",
    categoria: "Mitologia",
    preco: 42.9,
    maisVendido: true,
    imagem: "IMG/capas/percy-jackson-e-os-deuses-gregos.jpg",
  },
  {
    id: 168,
    titulo: "Percy Jackson e os Heróis Gregos",
    autor: "Rick Riordan",
    categoria: "Mitologia",
    preco: 42.9,
    maisVendido: false,
    imagem: "IMG/capas/percy-jackson-e-os-herois-gregos.jpg",
  },

  // =========================
  // CONTOS
  // =========================

  {
    id: 169,
    titulo: "Contos de Fadas",
    autor: "Irmãos Grimm",
    categoria: "Contos",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/contos-de-fadas.jpg",
  },
  {
    id: 170,
    titulo: "Contos",
    autor: "Edgar Allan Poe",
    categoria: "Contos",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/contos.jpg",
  },
  {
    id: 171,
    titulo: "Primeiras Estórias",
    autor: "João Guimarães Rosa",
    categoria: "Contos",
    preco: 34.9,
    maisVendido: false,
    imagem: "IMG/capas/primeiras-estorias.jpg",
  },
  {
    id: 172,
    titulo: "Laços de Família",
    autor: "Clarice Lispector",
    categoria: "Contos",
    preco: 34.9,
    maisVendido: true,
    imagem: "IMG/capas/lacos-de-familia.jpg",
  },
  {
    id: 173,
    titulo: "Felicidade Clandestina",
    autor: "Clarice Lispector",
    categoria: "Contos",
    preco: 32.9,
    maisVendido: false,
    imagem: "IMG/capas/felicidade-clandestina.jpg",
  },

  // =========================
  // POLICIAL
  // =========================

  {
    id: 174,
    titulo: "Sherlock Holmes: Um Estudo em Vermelho",
    autor: "Arthur Conan Doyle",
    categoria: "Policial",
    preco: 34.9,
    maisVendido: true,
    imagem: "IMG/capas/sherlock-holmes-um-estudo-em-vermelho.jpg",
  },
  {
    id: 175,
    titulo: "O Cão dos Baskervilles",
    autor: "Arthur Conan Doyle",
    categoria: "Policial",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/o-cao-dos-baskervilles.jpg",
  },
  {
    id: 176,
    titulo: "O Vale do Medo",
    autor: "Arthur Conan Doyle",
    categoria: "Policial",
    preco: 37.9,
    maisVendido: false,
    imagem: "IMG/capas/o-vale-do-medo.jpg",
  },
  {
    id: 177,
    titulo: "O Misterioso Caso de Styles",
    autor: "Agatha Christie",
    categoria: "Policial",
    preco: 37.9,
    maisVendido: false,
    imagem: "IMG/capas/o-misterioso-caso-de-styles.jpg",
  },
  {
    id: 178,
    titulo: "Os Crimes ABC",
    autor: "Agatha Christie",
    categoria: "Policial",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/os-crimes-abc.jpg",
  },

  // =========================
  // EDUCAÇÃO
  // =========================

  {
    id: 179,
    titulo: "Pedagogia da Autonomia",
    autor: "Paulo Freire",
    categoria: "Educação",
    preco: 34.9,
    maisVendido: true,
    imagem: "IMG/capas/pedagogia-da-autonomia.jpg",
  },
  {
    id: 180,
    titulo: "Educação como Prática da Liberdade",
    autor: "Paulo Freire",
    categoria: "Educação",
    preco: 32.9,
    maisVendido: false,
    imagem: "IMG/capas/educacao-como-pratica-da-liberdade.jpg",
  },
  {
    id: 181,
    titulo: "O Cérebro da Criança",
    autor: "Daniel J. Siegel e Tina Payne Bryson",
    categoria: "Educação",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/o-cerebro-da-crianca.jpg",
  },
  {
    id: 182,
    titulo: "Aprendendo a Aprender",
    autor: "Barbara Oakley",
    categoria: "Educação",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/aprendendo-a-aprender.jpg",
  },

  // =========================
  // CRÔNICAS
  // =========================

  {
    id: 183,
    titulo: "A Vida Como Ela É",
    autor: "Nelson Rodrigues",
    categoria: "Crônicas",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/a-vida-como-ela-e.jpg",
  },
  {
    id: 184,
    titulo: "Com o Mar por Testemunha",
    autor: "Rubem Braga",
    categoria: "Crônicas",
    preco: 32.9,
    maisVendido: false,
    imagem: "IMG/capas/com-o-mar-por-testemunha.jpg",
  },
  {
    id: 185,
    titulo: "Para Gostar de Ler",
    autor: "Carlos Drummond de Andrade",
    categoria: "Crônicas",
    preco: 29.9,
    maisVendido: true,
    imagem: "IMG/capas/para-gostar-de-ler.jpg",
  },
  {
    id: 186,
    titulo: "A Descoberta do Mundo",
    autor: "Clarice Lispector",
    categoria: "Crônicas",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/a-descoberta-do-mundo.jpg",
  },

  // =========================
  // DESENVOLVIMENTO PESSOAL
  // =========================

  {
    id: 187,
    titulo: "12 Regras para a Vida",
    autor: "Jordan B. Peterson",
    categoria: "Desenvolvimento Pessoal",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/12-regras-para-a-vida.jpg",
  },
  {
    id: 188,
    titulo: "O Jeito Harvard de Ser Feliz",
    autor: "Shawn Achor",
    categoria: "Desenvolvimento Pessoal",
    preco: 42.9,
    maisVendido: false,
    imagem: "IMG/capas/o-jeito-harvard-de-ser-feliz.jpg",
  },
  {
    id: 189,
    titulo: "A Sutil Arte de Ligar o F*da-se",
    autor: "Mark Manson",
    categoria: "Desenvolvimento Pessoal",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/a-sutil-arte-de-ligar-o-f-da-se.jpg",
  },
  {
    id: 190,
    titulo: "A Coragem de Não Agradar",
    autor: "Ichiro Kishimi e Fumitake Koga",
    categoria: "Desenvolvimento Pessoal",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/a-coragem-de-nao-agradar.jpg",
  },

  // =========================
  // FICÇÃO
  // =========================

  {
    id: 191,
    titulo: "O Grande Gatsby",
    autor: "F. Scott Fitzgerald",
    categoria: "Ficção",
    preco: 34.9,
    maisVendido: true,
    imagem: "IMG/capas/o-grande-gatsby.jpg",
  },
  {
    id: 192,
    titulo: "Cem Anos de Solidão",
    autor: "Gabriel García Márquez",
    categoria: "Ficção",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/cem-anos-de-solidao.jpg",
  },
  {
    id: 193,
    titulo: "O Amor nos Tempos do Cólera",
    autor: "Gabriel García Márquez",
    categoria: "Ficção",
    preco: 49.9,
    maisVendido: false,
    imagem: "IMG/capas/o-amor-nos-tempos-do-colera.jpg",
  },
  {
    id: 194,
    titulo: "O Velho e o Mar",
    autor: "Ernest Hemingway",
    categoria: "Ficção",
    preco: 34.9,
    maisVendido: true,
    imagem: "IMG/capas/o-velho-e-o-mar.jpg",
  },
  {
    id: 195,
    titulo: "A Metamorfose",
    autor: "Franz Kafka",
    categoria: "Ficção",
    preco: 29.9,
    maisVendido: true,
    imagem: "IMG/capas/a-metamorfose.jpg",
  },
  {
    id: 196,
    titulo: "O Estrangeiro",
    autor: "Albert Camus",
    categoria: "Ficção",
    preco: 34.9,
    maisVendido: false,
    imagem: "IMG/capas/o-estrangeiro.jpg",
  },
  {
    id: 197,
    titulo: "Ensaio Sobre a Cegueira",
    autor: "José Saramago",
    categoria: "Ficção",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/ensaio-sobre-a-cegueira.jpg",
  },
  {
    id: 198,
    titulo: "O Alquimista",
    autor: "Paulo Coelho",
    categoria: "Ficção",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/o-alquimista.jpg",
  },
  {
    id: 199,
    titulo: "Veronika Decide Morrer",
    autor: "Paulo Coelho",
    categoria: "Ficção",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/veronika-decide-morrer.jpg",
  },
  {
    id: 200,
    titulo: "A Insustentável Leveza do Ser",
    autor: "Milan Kundera",
    categoria: "Ficção",
    preco: 44.9,
    maisVendido: false,
    imagem: "IMG/capas/a-insustentavel-leveza-do-ser.jpg",
  },

  // =========================
  // MAIS FANTASIA
  // =========================

  {
    id: 201,
    titulo: "O Aprendiz de Assassino",
    autor: "Robin Hobb",
    categoria: "Fantasia",
    preco: 54.9,
    maisVendido: false,
    imagem: "IMG/capas/o-aprendiz-de-assassino.jpg",
  },
  {
    id: 202,
    titulo: "A Rainha Vermelha",
    autor: "Victoria Aveyard",
    categoria: "Fantasia",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/a-rainha-vermelha.jpg",
  },
  {
    id: 203,
    titulo: "Cidade dos Ossos",
    autor: "Cassandra Clare",
    categoria: "Fantasia",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/cidade-dos-ossos.jpg",
  },
  {
    id: 204,
    titulo: "Sombra e Ossos",
    autor: "Leigh Bardugo",
    categoria: "Fantasia",
    preco: 44.9,
    maisVendido: false,
    imagem: "IMG/capas/sombra-e-ossos.jpg",
  },
  {
    id: 205,
    titulo: "Seis de Corvos",
    autor: "Leigh Bardugo",
    categoria: "Fantasia",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/seis-de-corvos.jpg",
  },

  // =========================
  // MAIS ROMANCE
  // =========================

  {
    id: 206,
    titulo: "É Assim que Acaba",
    autor: "Colleen Hoover",
    categoria: "Romance",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/e-assim-que-acaba.jpg",
  },
  {
    id: 207,
    titulo: "É Assim que Começa",
    autor: "Colleen Hoover",
    categoria: "Romance",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/e-assim-que-comeca.jpg",
  },
  {
    id: 208,
    titulo: "Todas as Suas Imperfeições",
    autor: "Colleen Hoover",
    categoria: "Romance",
    preco: 49.9,
    maisVendido: false,
    imagem: "IMG/capas/todas-as-suas-imperfeicoes.jpg",
  },
  {
    id: 209,
    titulo: "Teto para Dois",
    autor: "Beth O'Leary",
    categoria: "Romance",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/teto-para-dois.jpg",
  },
  {
    id: 210,
    titulo: "Amor & Gelato",
    autor: "Jenna Evans Welch",
    categoria: "Romance",
    preco: 42.9,
    maisVendido: false,
    imagem: "IMG/capas/amor-gelato.jpg",
  },

  // =========================
  // MAIS SUSPENSE
  // =========================

  {
    id: 211,
    titulo: "Verity",
    autor: "Colleen Hoover",
    categoria: "Suspense",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/verity.jpg",
  },
  {
    id: 212,
    titulo: "O Homem de Giz",
    autor: "C. J. Tudor",
    categoria: "Suspense",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/o-homem-de-giz.jpg",
  },
  {
    id: 213,
    titulo: "A Corrente",
    autor: "Adrian McKinty",
    categoria: "Suspense",
    preco: 44.9,
    maisVendido: false,
    imagem: "IMG/capas/a-corrente.jpg",
  },
  {
    id: 214,
    titulo: "A Última Festa",
    autor: "Lucy Foley",
    categoria: "Suspense",
    preco: 44.9,
    maisVendido: false,
    imagem: "IMG/capas/a-ultima-festa.jpg",
  },
  {
    id: 215,
    titulo: "A Lista de Convidados",
    autor: "Lucy Foley",
    categoria: "Suspense",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/a-lista-de-convidados.jpg",
  },

  // =========================
  // MAIS AVENTURA
  // =========================

  {
    id: 216,
    titulo: "O Chamado Selvagem",
    autor: "Jack London",
    categoria: "Aventura",
    preco: 34.9,
    maisVendido: true,
    imagem: "IMG/capas/o-chamado-selvagem.jpg",
  },
  {
    id: 217,
    titulo: "Caninos Brancos",
    autor: "Jack London",
    categoria: "Aventura",
    preco: 34.9,
    maisVendido: false,
    imagem: "IMG/capas/caninos-brancos.jpg",
  },
  {
    id: 218,
    titulo: "Moby Dick",
    autor: "Herman Melville",
    categoria: "Aventura",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/moby-dick.jpg",
  },
  {
    id: 219,
    titulo: "As Viagens de Gulliver",
    autor: "Jonathan Swift",
    categoria: "Aventura",
    preco: 34.9,
    maisVendido: false,
    imagem: "IMG/capas/as-viagens-de-gulliver.jpg",
  },
  {
    id: 220,
    titulo: "A Volta ao Mundo em 80 Dias",
    autor: "Júlio Verne",
    categoria: "Aventura",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/a-volta-ao-mundo-em-80-dias.jpg",
  },

  // =========================
  // MAIS TERROR
  // =========================

  {
    id: 221,
    titulo: "Doutor Sono",
    autor: "Stephen King",
    categoria: "Terror",
    preco: 54.9,
    maisVendido: true,
    imagem: "IMG/capas/doutor-sono.jpg",
  },
  {
    id: 222,
    titulo: "Misery",
    autor: "Stephen King",
    categoria: "Terror",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/misery.jpg",
  },
  {
    id: 223,
    titulo: "O Nevoeiro",
    autor: "Stephen King",
    categoria: "Terror",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/o-nevoeiro.jpg",
  },
  {
    id: 224,
    titulo: "A Dança da Morte",
    autor: "Stephen King",
    categoria: "Terror",
    preco: 59.9,
    maisVendido: false,
    imagem: "IMG/capas/a-danca-da-morte.jpg",
  },
  {
    id: 225,
    titulo: "Salem",
    autor: "Stephen King",
    categoria: "Terror",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/salem.jpg",
  },

  // =========================
  // MAIS FICÇÃO CIENTÍFICA
  // =========================

  {
    id: 226,
    titulo: "O Homem do Castelo Alto",
    autor: "Philip K. Dick",
    categoria: "Ficção Científica",
    preco: 44.9,
    maisVendido: false,
    imagem: "IMG/capas/o-homem-do-castelo-alto.jpg",
  },
  {
    id: 227,
    titulo: "Androides Sonham com Ovelhas Elétricas?",
    autor: "Philip K. Dick",
    categoria: "Ficção Científica",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/androides-sonham-com-ovelhas-eletricas.jpg",
  },
  {
    id: 228,
    titulo: "O Problema dos Três Corpos",
    autor: "Cixin Liu",
    categoria: "Ficção Científica",
    preco: 59.9,
    maisVendido: true,
    imagem: "IMG/capas/o-problema-dos-tres-corpos.jpg",
  },
  {
    id: 230,
    titulo: "O Marciano",
    autor: "Andy Weir",
    categoria: "Ficção Científica",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/o-marciano.jpg",
  },

  // =========================
  // MAIS CLÁSSICOS
  // =========================

  {
    id: 231,
    titulo: "Jane Eyre",
    autor: "Charlotte Brontë",
    categoria: "Clássico",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/jane-eyre.jpg",
  },
  {
    id: 232,
    titulo: "O Morro dos Ventos Uivantes",
    autor: "Emily Brontë",
    categoria: "Clássico",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/o-morro-dos-ventos-uivantes.jpg",
  },
  {
    id: 233,
    titulo: "A Divina Comédia",
    autor: "Dante Alighieri",
    categoria: "Clássico",
    preco: 49.9,
    maisVendido: false,
    imagem: "IMG/capas/a-divina-comedia.jpg",
  },
  {
    id: 234,
    titulo: "Fausto",
    autor: "Goethe",
    categoria: "Clássico",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/fausto.jpg",
  },
  {
    id: 235,
    titulo: "Odisseia",
    autor: "Homero",
    categoria: "Clássico",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/odisseia.jpg",
  },

  // =========================
  // MAIS AUTOAJUDA
  // =========================

  {
    id: 236,
    titulo: "O Milagre da Manhã",
    autor: "Hal Elrod",
    categoria: "Autoajuda",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/o-milagre-da-manha.jpg",
  },
  {
    id: 237,
    titulo: "A Única Coisa",
    autor: "Gary Keller e Jay Papasan",
    categoria: "Autoajuda",
    preco: 44.9,
    maisVendido: false,
    imagem: "IMG/capas/a-unica-coisa.jpg",
  },
  {
    id: 238,
    titulo: "Trabalhe 4 Horas por Semana",
    autor: "Timothy Ferriss",
    categoria: "Autoajuda",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/trabalhe-4-horas-por-semana.jpg",
  },
  {
    id: 239,
    titulo: "Comece pelo Porquê",
    autor: "Simon Sinek",
    categoria: "Autoajuda",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/comece-pelo-porque.jpg",
  },
  {
    id: 240,
    titulo: "Roube como um Artista",
    autor: "Austin Kleon",
    categoria: "Autoajuda",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/roube-como-um-artista.jpg",
  },

  // =========================
  // MAIS BIOGRAFIAS
  // =========================

  {
    id: 241,
    titulo: "Ayrton Senna: Uma Lenda a Toda Velocidade",
    autor: "Christopher Hilton",
    categoria: "Biografia",
    preco: 59.9,
    maisVendido: true,
    imagem: "IMG/capas/ayrton-senna-uma-lenda-a-toda-velocidade.jpg",
  },
  {
    id: 242,
    titulo: "Elon Musk",
    autor: "Walter Isaacson",
    categoria: "Biografia",
    preco: 79.9,
    maisVendido: true,
    imagem: "IMG/capas/elon-musk.jpg",
  },
  {
    id: 243,
    titulo: "Frida: A Biografia",
    autor: "Hayden Herrera",
    categoria: "Biografia",
    preco: 59.9,
    maisVendido: false,
    imagem: "IMG/capas/frida-a-biografia.jpg",
  },
  {
    id: 244,
    titulo: "Churchill",
    autor: "Andrew Roberts",
    categoria: "Biografia",
    preco: 69.9,
    maisVendido: false,
    imagem: "IMG/capas/churchill.jpg",
  },
  {
    id: 245,
    titulo: "Napoleão",
    autor: "Andrew Roberts",
    categoria: "Biografia",
    preco: 69.9,
    maisVendido: true,
    imagem: "IMG/capas/napoleao.jpg",
  },

  // =========================
  // MAIS POESIA
  // =========================

  {
    id: 246,
    titulo: "Poemas Escolhidos",
    autor: "Fernando Pessoa",
    categoria: "Poesia",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/poemas-escolhidos.jpg",
  },
  {
    id: 247,
    titulo: "Mensagem",
    autor: "Fernando Pessoa",
    categoria: "Poesia",
    preco: 29.9,
    maisVendido: true,
    imagem: "IMG/capas/mensagem.jpg",
  },
  {
    id: 248,
    titulo: "Claro Enigma",
    autor: "Carlos Drummond de Andrade",
    categoria: "Poesia",
    preco: 34.9,
    maisVendido: false,
    imagem: "IMG/capas/claro-enigma.jpg",
  },
  {
    id: 249,
    titulo: "Mar Absoluto",
    autor: "Cecília Meireles",
    categoria: "Poesia",
    preco: 34.9,
    maisVendido: false,
    imagem: "IMG/capas/mar-absoluto.jpg",
  },
  {
    id: 250,
    titulo: "Poemas",
    autor: "Manuel Bandeira",
    categoria: "Poesia",
    preco: 32.9,
    maisVendido: true,
    imagem: "IMG/capas/poemas.jpg",
  },
  // =========================
  // NOVOS LIVROS
  // =========================

  {
    id: 251,
    titulo: "A Guerra dos Tronos",
    autor: "George R. R. Martin",
    categoria: "Fantasia",
    preco: 69.9,
    maisVendido: true,
    imagem: "IMG/capas/a-guerra-dos-tronos.jpg",
  },
  {
    id: 252,
    titulo: "Trono de Vidro",
    autor: "Sarah J. Maas",
    categoria: "Fantasia",
    preco: 54.9,
    maisVendido: false,
    imagem: "IMG/capas/trono-de-vidro.jpg",
  },
  {
    id: 253,
    titulo: "Corte de Espinhos e Rosas",
    autor: "Sarah J. Maas",
    categoria: "Fantasia",
    preco: 52.9,
    maisVendido: true,
    imagem: "IMG/capas/corte-de-espinhos-e-rosas.jpg",
  },
  {
    id: 254,
    titulo: "Quarta Asa",
    autor: "Rebecca Yarros",
    categoria: "Fantasia",
    preco: 64.9,
    maisVendido: true,
    imagem: "IMG/capas/quarta-asa.jpg",
  },
  {
    id: 255,
    titulo: "O Feiticeiro de Terramar",
    autor: "Ursula K. Le Guin",
    categoria: "Fantasia",
    preco: 47.9,
    maisVendido: false,
    imagem: "IMG/capas/o-feiticeiro-de-terramar.jpg",
  },
  {
    id: 256,
    titulo: "Circe",
    autor: "Madeline Miller",
    categoria: "Fantasia",
    preco: 49.9,
    maisVendido: false,
    imagem: "IMG/capas/circe.jpg",
  },
  {
    id: 257,
    titulo: "A Canção de Aquiles",
    autor: "Madeline Miller",
    categoria: "Romance",
    preco: 46.9,
    maisVendido: false,
    imagem: "IMG/capas/a-cancao-de-aquiles.jpg",
  },
  {
    id: 258,
    titulo: "Projeto Hail Mary",
    autor: "Andy Weir",
    categoria: "Ficção Científica",
    preco: 59.9,
    maisVendido: true,
    imagem: "IMG/capas/projeto-hail-mary.jpg",
  },
  {
    id: 259,
    titulo: "Ready Player One",
    autor: "Ernest Cline",
    categoria: "Ficção Científica",
    preco: 44.9,
    maisVendido: false,
    imagem: "IMG/capas/ready-player-one.jpg",
  },
  {
    id: 260,
    titulo: "Ender, o Estrategista",
    autor: "Orson Scott Card",
    categoria: "Ficção Científica",
    preco: 42.9,
    maisVendido: false,
    imagem: "IMG/capas/ender-o-estrategista.jpg",
  },
  {
    id: 261,
    titulo: "Contato",
    autor: "Carl Sagan",
    categoria: "Ficção Científica",
    preco: 45.9,
    maisVendido: false,
    imagem: "IMG/capas/contato.jpg",
  },
  {
    id: 262,
    titulo: "A Mão Esquerda da Escuridão",
    autor: "Ursula K. Le Guin",
    categoria: "Ficção Científica",
    preco: 49.9,
    maisVendido: false,
    imagem: "IMG/capas/a-mao-esquerda-da-escuridao.jpg",
  },
  {
    id: 263,
    titulo: "Cosmos",
    autor: "Carl Sagan",
    categoria: "Ciência",
    preco: 69.9,
    maisVendido: false,
    imagem: "IMG/capas/cosmos.jpg",
  },
  {
    id: 264,
    titulo: "O Gene",
    autor: "Siddhartha Mukherjee",
    categoria: "Ciência",
    preco: 79.9,
    maisVendido: false,
    imagem: "IMG/capas/o-gene.jpg",
  },
  {
    id: 265,
    titulo: "A Origem das Espécies",
    autor: "Charles Darwin",
    categoria: "Ciência",
    preco: 54.9,
    maisVendido: false,
    imagem: "IMG/capas/a-origem-das-especies.jpg",
  },
  {
    id: 266,
    titulo: "A Empregada",
    autor: "Freida McFadden",
    categoria: "Suspense",
    preco: 44.9,
    maisVendido: true,
    imagem: "IMG/capas/a-empregada.jpg",
  },
  {
    id: 267,
    titulo: "O Instituto",
    autor: "Stephen King",
    categoria: "Terror",
    preco: 69.9,
    maisVendido: false,
    imagem: "IMG/capas/o-instituto.jpg",
  },
  {
    id: 268,
    titulo: "O Nome da Rosa",
    autor: "Umberto Eco",
    categoria: "Mistério",
    preco: 64.9,
    maisVendido: false,
    imagem: "IMG/capas/o-nome-da-rosa.jpg",
  },
  {
    id: 269,
    titulo: "A Biblioteca da Meia-Noite",
    autor: "Matt Haig",
    categoria: "Ficção",
    preco: 42.9,
    maisVendido: true,
    imagem: "IMG/capas/a-biblioteca-da-meia-noite.jpg",
  },
  {
    id: 270,
    titulo: "Os Sete Maridos de Evelyn Hugo",
    autor: "Taylor Jenkins Reid",
    categoria: "Romance",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/os-sete-maridos-de-evelyn-hugo.jpg",
  },
  {
    id: 271,
    titulo: "Daisy Jones & The Six",
    autor: "Taylor Jenkins Reid",
    categoria: "Romance",
    preco: 44.9,
    maisVendido: false,
    imagem: "IMG/capas/daisy-jones-the-six.jpg",
  },
  {
    id: 272,
    titulo: "A Seleção",
    autor: "Kiera Cass",
    categoria: "Romance",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/a-selecao.jpg",
  },
  {
    id: 273,
    titulo: "Lolita",
    autor: "Vladimir Nabokov",
    categoria: "Clássico",
    preco: 59.9,
    maisVendido: false,
    imagem: "IMG/capas/lolita.jpg",
  },
  {
    id: 274,
    titulo: "Madame Bovary",
    autor: "Gustave Flaubert",
    categoria: "Clássico",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/madame-bovary.jpg",
  },
  {
    id: 275,
    titulo: "Torto Arado",
    autor: "Itamar Vieira Junior",
    categoria: "Drama",
    preco: 49.9,
    maisVendido: true,
    imagem: "IMG/capas/torto-arado.jpg",
  },
  {
    id: 276,
    titulo: "Dois Irmãos",
    autor: "Milton Hatoum",
    categoria: "Drama",
    preco: 42.9,
    maisVendido: false,
    imagem: "IMG/capas/dois-irmaos.jpg",
  },
  {
    id: 277,
    titulo: "Capitães da Areia",
    autor: "Jorge Amado",
    categoria: "Clássico",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/capitaes-da-areia.jpg",
  },
  {
    id: 278,
    titulo: "Vidas Secas",
    autor: "Graciliano Ramos",
    categoria: "Clássico",
    preco: 34.9,
    maisVendido: false,
    imagem: "IMG/capas/vidas-secas.jpg",
  },
  {
    id: 279,
    titulo: "Quarto de Despejo",
    autor: "Carolina Maria de Jesus",
    categoria: "Biografia",
    preco: 39.9,
    maisVendido: false,
    imagem: "IMG/capas/quarto-de-despejo.jpg",
  },
  {
    id: 280,
    titulo: "A Hora da Estrela",
    autor: "Clarice Lispector",
    categoria: "Clássico",
    preco: 32.9,
    maisVendido: false,
    imagem: "IMG/capas/a-hora-da-estrela.jpg",
  },
  {
    id: 281,
    titulo: "O Processo",
    autor: "Franz Kafka",
    categoria: "Clássico",
    preco: 36.9,
    maisVendido: false,
    imagem: "IMG/capas/o-processo.jpg",
  },
  {
    id: 282,
    titulo: "Os Irmãos Karamázov",
    autor: "Fiódor Dostoiévski",
    categoria: "Clássico",
    preco: 89.9,
    maisVendido: false,
    imagem: "IMG/capas/os-irmaos-karamazov.jpg",
  },
  {
    id: 283,
    titulo: "Maus",
    autor: "Art Spiegelman",
    categoria: "Quadrinhos",
    preco: 79.9,
    maisVendido: false,
    imagem: "IMG/capas/maus.jpg",
  },
  {
    id: 284,
    titulo: "Watchmen",
    autor: "Alan Moore",
    categoria: "Quadrinhos",
    preco: 119.9,
    maisVendido: true,
    imagem: "IMG/capas/watchmen.jpg",
  },
  {
    id: 285,
    titulo: "Persépolis",
    autor: "Marjane Satrapi",
    categoria: "Quadrinhos",
    preco: 64.9,
    maisVendido: false,
    imagem: "IMG/capas/persepolis.jpg",
  },
  {
    id: 286,
    titulo: "O Diário de Anne Frank",
    autor: "Anne Frank",
    categoria: "Biografia",
    preco: 39.9,
    maisVendido: true,
    imagem: "IMG/capas/o-diario-de-anne-frank.jpg",
  },
  {
    id: 287,
    titulo: "Eu Sou Malala",
    autor: "Malala Yousafzai",
    categoria: "Biografia",
    preco: 44.9,
    maisVendido: false,
    imagem: "IMG/capas/eu-sou-malala.jpg",
  },
  {
    id: 288,
    titulo: "Mulheres que Correm com os Lobos",
    autor: "Clarissa Pinkola Estés",
    categoria: "Psicologia",
    preco: 74.9,
    maisVendido: false,
    imagem: "IMG/capas/mulheres-que-correm-com-os-lobos.jpg",
  },
  {
    id: 289,
    titulo: "Quem Mexeu no Meu Queijo?",
    autor: "Spencer Johnson",
    categoria: "Autoajuda",
    preco: 29.9,
    maisVendido: false,
    imagem: "IMG/capas/quem-mexeu-no-meu-queijo.jpg",
  },
  {
    id: 290,
    titulo: "Sobre a Escrita",
    autor: "Stephen King",
    categoria: "Biografia",
    preco: 49.9,
    maisVendido: false,
    imagem: "IMG/capas/sobre-a-escrita.jpg",
  },
];
